Initial release candidate
Xon/XenForo2-TitleEditHistory pull request #1
Opened 2018-02-11 15:35 UTC by yugensoft

2018-02-11 21:59 UTC, Xon commented
FYI, you should put any php version check into addon.json via;
```
    "require" : {
        "php": ["5.6.0", "PHP 5.6.0+"]
    },
```

This way your installer can use those language features.
Note; I've moving to a minimum of php5.6+ for all my add-ons.

2018-02-11 22:25 UTC, Xon requested changes

2018-02-11 22:25 UTC, Xon commented on upload/src/addons/SV/TitleEditHistory/EditHistoryHandler/Thread.php
> +	public function revertToVersion(Entity $content, \XF\Entity\EditHistory $history, \XF\Entity\EditHistory $previous = null) {
`revertToVersion` should `XF\Service\Thread\Editor` similar to how `\XF\EditHistory\Post` does

2018-02-11 22:25 UTC, Xon commented on upload/src/addons/SV/TitleEditHistory/XF/Entity/Thread.php
> +	protected function _isNotInsideSilentEditWindow() {
The edit history logic should be moved into `XF\Service\Thread\Editor` similar to `XF\Service\Post\Editor::setMessage`, `XF\Service\Post\Editor::setMessage::setupEditHistory`.

2018-02-11 22:25 UTC, Xon commented on upload/src/addons/SV/TitleEditHistory/XF/Entity/Thread.php
> +	protected function _insertTitleEditHistory()
Once moved to the Thread Editor, this should be replaced with;
```
/** @var \XF\Repository\EditHistory $repo */
$repo = $this->repository('XF:EditHistory');
$repo->insertEditHistory('thread', $thread, $visitor, $this->oldTitle, $this->app->request()->getIp());
```

2018-02-11 22:25 UTC, Xon commented on upload/src/addons/SV/TitleEditHistory/_output/content_type_fields/thread_title-edit_history_handler_class.json
> +    "field_value": "SV\\TitleEditHistory\\EditHistoryHandler\\Thread"
Rename from EditHistoryHandler => EditHistory, and thankfully it doesn't require a custom upgrade step (unlike XF1)

2018-02-11 22:31 UTC, Xon commented
Note; `\XF\Service\Thread\Editor::_save()` current has some horrible bugs with respect to transaction handling.

Add the insert edit history logic around a `parent::_save()` call with a transaction. Since all _save() does is call `$thread->save()`

2018-02-13 11:25 UTC, yugensoft commented
Alright let me know if that's what you had in mind.

This edithistory & 'service' system seemed like an awful lot of object-oriented abstraction to accomplish simply viewing a previous state. Do you know why Xenforo Co decided to head even deeper down the OO path with XF2, and didn't move more down the functional programming & immutable data route like Facebook etc?

2018-02-13 11:49 UTC, Xon commented
LGTM

Keep in mind that XF1 is dated 2008-2010 for it's major architecture design, and XF2 was 2015-2016 for it's initial design/implementation. XenForo is very conservative on baseline requirements and performance. Maybe XF3 in 2028 or so will be a different story.

2018-02-13 11:50 UTC, merged